name:                ProgrammingInHaskell
version:             0.1.0.0
github:              "stbraun/ProgrammingInHaskell"
license:             BSD3
author:              "Stefan Braun"
maintainer:          "sb@action.ms"
copyright:           "Stefan Braun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stbraun/ProgrammingInHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory

library:
  source-dirs: src

executables:
  ProgrammingInHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    # other-modules:      []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProgrammingInHaskell
  Traverse:
    main:               Main.hs
    source-dirs:        app/traverse
    other-modules:      []

tests:
  ProgrammingInHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProgrammingInHaskell
